apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scout.fullname" . }}-secret
  labels:
    {{- include "scout.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "scout.databaseUrl" . | quote }}
